### ISSUE TITLE
Not all repos showing up

### ISSUE THREAD

**Issue by patcon** [Zarkonnen/sb-github-integration#1]
https://www.evernote.com/shard/s27/sh/5d91c9cd-167e-4816-b509-02f9c6bdd6a2/a7c97e3d69e314a3b2854a1f4c6c124d

At first I thought it was just not recognizing my organizations' repos, but then when a forked an org repo to my personal, it didn't show up in the list. Further, I noticed that there was not nearly as many "patcon"-associated repos showing up (I probably have ~80).

Any thoughts on why this might be?

**Comment by patcon** [comment]
Awesome, awesome, AWESOME plugin by the way. So excited about this stuff :)

**Comment by admc** [comment]
I have also noticed this (a few repos missing from the list), thanks for
logging the bug Patrick.

**Comment by Zarkonnen** [comment]
Thanks, will look into this.

**Comment by patcon** [comment]
Thanks guys!

**Comment by estahn** [comment]
Any updates to this? I can't see my organisation repos either.

**Comment by Zarkonnen** [comment]
Apologies for the delay. I've now identified the problem and am working on a fix.

**Comment by Zarkonnen** [comment]
OK, I've fixed the issue and updated the plugin to version 1.0.4. You can upgrade the plugin via the "Manage plugins" option in Builder.

Let me know if it works for you, and if there's anything else that needs fixing. :)

**Comment by patcon** [comment]
:+1:
You're my hero @Zarkonnen
