### ISSUE TITLE
Selenium Builder plug-ins screen: "unable to install: Builder is not up to date"

### ISSUE THREAD

**Issue by thatpaulschofield** [Zarkonnen/sb-github-integration#2]
I've installed the Selenium Builder add-on directly from http://sebuilder.github.io/se-builder/, but when I navigate to the Selenium Builder plug-ins screen, I git the following message:

"GitHub Integration 1.0.5Not Installed; unable to install: Builder is not up to date"

**Comment by hugs** [comment]
I get this error, too. The text that I see:
"GitHub Integration 1.0.9Not Installed; unable to install: Builder is not up to date"

(Firefox 25.0.1, OS X 10.8.5, Selenium Builder 2.0.9)

Is there any workaround I can try until this problem is solved?
